version: "3.8"
services:
  backend:
    image: "katsunchan/springboot-react-fullstack:9.3.2023.7.27.16"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev