version: "3.8"
services:
  backend:
    image: "katsunchan/springboot-react-fullstack:25.5.2023.20.15.25"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev