version: "3.8"
services:
  backend:
    image: "katsunchan/springboot-react-fullstack:19.3.2023.1.59.53"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev